version: "3.8"

services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  
  nest:
    build:
      context: ./back/
      dockerfile: Dockerfile
    container_name: nest
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    restart: on-failure
  
  vue:
    build:
      context: ./front/
      dockerfile: Dockerfile
    container_name: vue
    ports:
      - '5173:5173'
    depends_on:
      - postgres

volumes:
  postgres: